name: fighting game
on:
  push:
    branches: [main]
jobs:
  fighting-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - run: git config --global user.email "nlqtin@tma.com.vn"
      - run: git config --global user.name "Quang Tin"
      - run: npm run deploy